"use client"

import * as React from "react"
import {
  AreaChart,
  Area,
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  Users,
  DollarSign,
  Activity,
  Zap,
  ArrowUpRight,
  ArrowDownRight,
  Clock,
  CheckCircle2,
  AlertCircle,
  UserPlus,
  Key,
  Globe,
} from "lucide-react"

// ─── Data ────────────────────────────────────────────────────────────────────

const revenueData = [
  { month: "Jan", revenue: 32000, users: 1800 },
  { month: "Feb", revenue: 28500, users: 1950 },
  { month: "Mar", revenue: 41200, users: 2200 },
  { month: "Apr", revenue: 37800, users: 2100 },
  { month: "May", revenue: 45600, users: 2450 },
  { month: "Jun", revenue: 52100, users: 2700 },
  { month: "Jul", revenue: 48900, users: 2600 },
  { month: "Aug", revenue: 61300, users: 3100 },
  { month: "Sep", revenue: 57200, users: 2950 },
  { month: "Oct", revenue: 68400, users: 3350 },
  { month: "Nov", revenue: 74100, users: 3600 },
  { month: "Dec", revenue: 82500, users: 4100 },
]

const weeklyApiCalls = [
  { day: "Mon", calls: 12400 },
  { day: "Tue", calls: 18900 },
  { day: "Wed", calls: 15700 },
  { day: "Thu", calls: 22300 },
  { day: "Fri", calls: 19800 },
  { day: "Sat", calls: 9200 },
  { day: "Sun", calls: 7600 },
]

// Sparkline mini data for each KPI card
const sparkRevenue = [28, 32, 29, 41, 38, 46, 52, 49, 61, 57, 68, 82]
const sparkUsers   = [1800, 1950, 2200, 2100, 2450, 2700, 2600, 3100, 2950, 3350, 3600, 4100]
const sparkApiCalls = [8400, 11200, 9800, 14300, 12100, 15800, 13900]
const sparkUptime   = [99.9, 99.7, 100, 99.8, 100, 99.9, 100]

const recentActivity = [
  {
    id: 1,
    type: "user_joined",
    icon: UserPlus,
    iconColor: "text-emerald-500",
    iconBg: "bg-emerald-500/10",
    title: "New user joined",
    description: "maria.garcia@example.com joined Default Organization",
    time: "2 min ago",
    status: "success",
  },
  {
    id: 2,
    type: "api_key",
    icon: Key,
    iconColor: "text-blue-500",
    iconBg: "bg-blue-500/10",
    title: "API key created",
    description: "Production key sk_live_*** generated by Admin",
    time: "15 min ago",
    status: "info",
  },
  {
    id: 3,
    type: "webhook",
    icon: Globe,
    iconColor: "text-amber-500",
    iconBg: "bg-amber-500/10",
    title: "Webhook failed",
    description: "POST https://api.example.com/hooks returned 503",
    time: "42 min ago",
    status: "warning",
  },
  {
    id: 4,
    type: "deployment",
    icon: CheckCircle2,
    iconColor: "text-emerald-500",
    iconBg: "bg-emerald-500/10",
    title: "Deployment completed",
    description: "v2.4.1 deployed to production successfully",
    time: "1 hr ago",
    status: "success",
  },
  {
    id: 5,
    type: "alert",
    icon: AlertCircle,
    iconColor: "text-red-500",
    iconBg: "bg-red-500/10",
    title: "Anomaly detected",
    description: "Unusual traffic spike in EU-West region",
    time: "2 hr ago",
    status: "error",
  },
  {
    id: 6,
    type: "user_joined",
    icon: UserPlus,
    iconColor: "text-emerald-500",
    iconBg: "bg-emerald-500/10",
    title: "New user joined",
    description: "john.doe@acme.com joined Acme Corp",
    time: "3 hr ago",
    status: "success",
  },
]

const topOrgs = [
  { name: "Acme Corp", requests: 142300, pct: 92, color: "#3B82F6" },
  { name: "Globex Inc", requests: 98700, pct: 64, color: "#8B5CF6" },
  { name: "Initech LLC", requests: 67200, pct: 44, color: "#06B6D4" },
  { name: "Umbrella Co", requests: 41800, pct: 27, color: "#10B981" },
  { name: "Stark Ltd", requests: 28900, pct: 19, color: "#F59E0B" },
]

// ─── Types ────────────────────────────────────────────────────────────────────

interface SparklineProps {
  data: number[]
  color: string
  positive?: boolean
}

// ─── Mini Sparkline component ────────────────────────────────────────────────

function Sparkline({ data, color, positive = true }: SparklineProps) {
  const normalized = data.map((v) => ({ v }))
  return (
    <ResponsiveContainer width={80} height={36}>
      <LineChart data={normalized}>
        <Line
          type="monotone"
          dataKey="v"
          stroke={positive ? color : "#EF4444"}
          strokeWidth={1.5}
          dot={false}
        />
      </LineChart>
    </ResponsiveContainer>
  )
}

// ─── Custom Tooltip ───────────────────────────────────────────────────────────

interface TooltipPayload {
  name: string
  value: number | string
  color?: string
}

interface CustomTooltipProps {
  active?: boolean
  payload?: TooltipPayload[]
  label?: string
  formatter?: (value: number | string) => string
}

function CustomTooltip({ active, payload, label, formatter }: CustomTooltipProps) {
  if (!active || !payload?.length) return null
  return (
    <div className="rounded-lg border border-border bg-popover px-3 py-2 shadow-lg text-xs">
      <p className="font-medium text-foreground mb-1">{label}</p>
      {payload.map((p) => (
        <div key={p.name} className="flex items-center gap-2">
          <span className="h-2 w-2 rounded-full" style={{ background: p.color }} />
          <span className="text-muted-foreground">{p.name}:</span>
          <span className="font-semibold text-foreground">
            {formatter ? formatter(p.value) : p.value}
          </span>
        </div>
      ))}
    </div>
  )
}

// ─── KPI Card ─────────────────────────────────────────────────────────────────

interface KpiCardProps {
  title: string
  value: string
  change: string
  changeLabel: string
  positive: boolean
  icon: React.ElementType
  iconColor: string
  iconBg: string
  sparkData: number[]
  sparkColor: string
}

function KpiCard({
  title,
  value,
  change,
  changeLabel,
  positive,
  icon: Icon,
  iconColor,
  iconBg,
  sparkData,
  sparkColor,
}: KpiCardProps) {
  return (
    <Card className="relative overflow-hidden hover-card cursor-default glass">
      <CardHeader className="flex flex-row items-start justify-between space-y-0 pb-2">
        <div className="space-y-1">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
            {title}
          </p>
          <p className="text-2xl font-bold text-foreground">{value}</p>
        </div>
        <div className={`flex h-9 w-9 items-center justify-center rounded-lg ${iconBg}`}>
          <Icon className={`h-4 w-4 ${iconColor}`} />
        </div>
      </CardHeader>
      <CardContent>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-1">
            {positive ? (
              <ArrowUpRight className="h-3.5 w-3.5 text-emerald-500" />
            ) : (
              <ArrowDownRight className="h-3.5 w-3.5 text-red-500" />
            )}
            <span className={`text-xs font-semibold ${positive ? "text-emerald-500" : "text-red-500"}`}>
              {change}
            </span>
            <span className="text-xs text-muted-foreground">{changeLabel}</span>
          </div>
          <Sparkline data={sparkData} color={sparkColor} positive={positive} />
        </div>
      </CardContent>
      {/* Subtle gradient accent */}
      <div
        className="pointer-events-none absolute bottom-0 left-0 right-0 h-px opacity-60"
        style={{ background: `linear-gradient(to right, transparent, ${sparkColor}, transparent)` }}
      />
    </Card>
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function DashboardPage() {
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Overview</h1>
          <p className="text-sm text-muted-foreground mt-0.5">
            Multi-tenant analytics platform · Last updated just now
          </p>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1.5 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 text-xs font-medium text-emerald-600 dark:text-emerald-400">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 animate-pulse" />
            All systems operational
          </div>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <KpiCard
          title="Total Revenue"
          value="$82,500"
          change="+11.3%"
          changeLabel="vs last month"
          positive={true}
          icon={DollarSign}
          iconColor="text-blue-500"
          iconBg="bg-blue-500/10"
          sparkData={sparkRevenue}
          sparkColor="#3B82F6"
        />
        <KpiCard
          title="Active Users"
          value="4,100"
          change="+13.9%"
          changeLabel="vs last month"
          positive={true}
          icon={Users}
          iconColor="text-violet-500"
          iconBg="bg-violet-500/10"
          sparkData={sparkUsers}
          sparkColor="#8B5CF6"
        />
        <KpiCard
          title="API Calls / day"
          value="105.8k"
          change="+18.2%"
          changeLabel="vs last week"
          positive={true}
          icon={Zap}
          iconColor="text-amber-500"
          iconBg="bg-amber-500/10"
          sparkData={sparkApiCalls}
          sparkColor="#F59E0B"
        />
        <KpiCard
          title="Uptime"
          value="99.97%"
          change="-0.03%"
          changeLabel="vs last month"
          positive={false}
          icon={Activity}
          iconColor="text-emerald-500"
          iconBg="bg-emerald-500/10"
          sparkData={sparkUptime}
          sparkColor="#10B981"
        />
      </div>

      {/* Main Content Grid */}
      <div className="grid gap-6 lg:grid-cols-7">

        {/* Revenue & Users Chart — spans 4 cols */}
        <Card className="lg:col-span-4">
          <CardHeader className="pb-4">
            <div className="flex items-start justify-between">
              <div>
                <CardTitle className="text-base font-semibold">Revenue & Users</CardTitle>
                <CardDescription className="text-xs mt-0.5">
                  12-month performance overview
                </CardDescription>
              </div>
              <Tabs defaultValue="revenue">
                <TabsList className="h-7 text-xs">
                  <TabsTrigger value="revenue" className="text-xs px-2 py-1">Revenue</TabsTrigger>
                  <TabsTrigger value="users" className="text-xs px-2 py-1">Users</TabsTrigger>
                </TabsList>
              </Tabs>
            </div>
          </CardHeader>
          <CardContent className="pb-2">
            <Tabs defaultValue="revenue">
              <TabsContent value="revenue" className="mt-0">
                <ResponsiveContainer width="100%" height={260}>
                  <AreaChart data={revenueData} margin={{ top: 4, right: 4, left: -20, bottom: 0 }}>
                    <defs>
                      <linearGradient id="gradRevenue" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#3B82F6" stopOpacity={0.25} />
                        <stop offset="95%" stopColor="#3B82F6" stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} />
                    <XAxis
                      dataKey="month"
                      tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }}
                      axisLine={false}
                      tickLine={false}
                    />
                    <YAxis
                      tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }}
                      axisLine={false}
                      tickLine={false}
                      tickFormatter={(v) => `$${(v / 1000).toFixed(0)}k`}
                    />
                    <Tooltip
                      content={<CustomTooltip formatter={(v) => `$${Number(v).toLocaleString()}`} />}
                    />
                    <Area
                      type="monotone"
                      dataKey="revenue"
                      name="Revenue"
                      stroke="#3B82F6"
                      strokeWidth={2}
                      fill="url(#gradRevenue)"
                      dot={false}
                      activeDot={{ r: 4, fill: "#3B82F6", strokeWidth: 0 }}
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </TabsContent>
              <TabsContent value="users" className="mt-0">
                <ResponsiveContainer width="100%" height={260}>
                  <AreaChart data={revenueData} margin={{ top: 4, right: 4, left: -20, bottom: 0 }}>
                    <defs>
                      <linearGradient id="gradUsers" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#8B5CF6" stopOpacity={0.25} />
                        <stop offset="95%" stopColor="#8B5CF6" stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} />
                    <XAxis
                      dataKey="month"
                      tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }}
                      axisLine={false}
                      tickLine={false}
                    />
                    <YAxis
                      tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }}
                      axisLine={false}
                      tickLine={false}
                      tickFormatter={(v) => `${(v / 1000).toFixed(1)}k`}
                    />
                    <Tooltip
                      content={<CustomTooltip formatter={(v) => Number(v).toLocaleString()} />}
                    />
                    <Area
                      type="monotone"
                      dataKey="users"
                      name="Users"
                      stroke="#8B5CF6"
                      strokeWidth={2}
                      fill="url(#gradUsers)"
                      dot={false}
                      activeDot={{ r: 4, fill: "#8B5CF6", strokeWidth: 0 }}
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>

        {/* Recent Activity — spans 3 cols */}
        <Card className="lg:col-span-3 flex flex-col">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-base font-semibold">Recent Activity</CardTitle>
              <Badge variant="secondary" className="text-xs font-normal">
                <Clock className="mr-1 h-3 w-3" />
                Live
              </Badge>
            </div>
            <CardDescription className="text-xs">Latest events across all organizations</CardDescription>
          </CardHeader>
          <CardContent className="flex-1 overflow-hidden">
            <div className="space-y-3">
              {recentActivity.map((event) => (
                <div
                  key={event.id}
                  className="flex items-start gap-3 group cursor-default"
                >
                  <div className={`mt-0.5 flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-md ${event.iconBg}`}>
                    <event.icon className={`h-3.5 w-3.5 ${event.iconColor}`} />
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-xs font-medium text-foreground leading-tight truncate">
                      {event.title}
                    </p>
                    <p className="text-xs text-muted-foreground leading-tight truncate mt-0.5">
                      {event.description}
                    </p>
                  </div>
                  <span className="flex-shrink-0 text-[10px] text-muted-foreground tabular-nums">
                    {event.time}
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Second Row */}
      <div className="grid gap-6 lg:grid-cols-7">

        {/* Weekly API Calls Bar Chart — 4 cols */}
        <Card className="lg:col-span-4">
          <CardHeader className="pb-4">
            <CardTitle className="text-base font-semibold">API Calls This Week</CardTitle>
            <CardDescription className="text-xs">Daily request volume across all tenants</CardDescription>
          </CardHeader>
          <CardContent className="pb-2">
            <ResponsiveContainer width="100%" height={200}>
              <BarChart data={weeklyApiCalls} margin={{ top: 4, right: 4, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} />
                <XAxis
                  dataKey="day"
                  tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }}
                  axisLine={false}
                  tickLine={false}
                />
                <YAxis
                  tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }}
                  axisLine={false}
                  tickLine={false}
                  tickFormatter={(v) => `${(v / 1000).toFixed(0)}k`}
                />
                <Tooltip
                  content={<CustomTooltip formatter={(v) => `${Number(v).toLocaleString()} calls`} />}
                />
                <Bar
                  dataKey="calls"
                  name="API Calls"
                  fill="#3B82F6"
                  radius={[4, 4, 0, 0]}
                  maxBarSize={40}
                />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Top Organizations — 3 cols */}
        <Card className="lg:col-span-3">
          <CardHeader className="pb-3">
            <CardTitle className="text-base font-semibold">Top Organizations</CardTitle>
            <CardDescription className="text-xs">By API request volume this month</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {topOrgs.map((org, i) => (
                <div key={org.name} className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <span className="flex h-5 w-5 items-center justify-center rounded-md bg-muted text-[10px] font-bold text-muted-foreground">
                        {i + 1}
                      </span>
                      <span className="font-medium text-foreground">{org.name}</span>
                    </div>
                    <span className="text-muted-foreground tabular-nums">
                      {(org.requests / 1000).toFixed(1)}k
                    </span>
                  </div>
                  <div className="h-1.5 w-full rounded-full bg-muted overflow-hidden">
                    <div
                      className="h-full rounded-full transition-all duration-700"
                      style={{ width: `${org.pct}%`, background: org.color }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

      </div>
    </div>
  )
}
